apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  generateName: hari-gcr-admin-bonete-test-
  namespace: gcr-admin
spec:
  queue: gcr-admin
  minAvailable: 1
  plugins:
    ssh: []
    svc: []
    env: []
  tasks:
    - name: server
      replicas: 1
      template:
        metadata:
          labels:
            app: hari-gcr-bonete-test
            role: server
        spec:
          schedulerName: volcano
          nodeSelector:
            # kubernetes.io/hostname: "nodename-placeholder"
            kubernetes.io/hostname: "slc01-cl02-hgx-0460"
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 256Gi
            - name: sys
              hostPath:
                path: /sys
                type: Directory
            - name: data
              persistentVolumeClaim:
                claimName: pvc-vast-gcr-admin
          tolerations:
            - key: "rdma"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: hari-gcr-bonete-test
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: server
              image: nvcr.io/nvidia/pytorch:25.11-py3
              env:
                - name: GCRNODE
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: sys
                  mountPath: /sys
                  readOnly: true
                - name: data
                  mountPath: /data
              ports:
                - name: rdma
                  containerPort: 18515
              command: ["/bin/bash", "-lc"]
              args:
                - |
                  git clone https://github.com/IamNirmata/Cluster-Validation-Runbook.git /opt/Cluster-Validation-Runbook
                  sleep 3600
                  bash /opt/Cluster-Validation-Runbook/storage-tests/run.sh
              resources:
                requests:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"