apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  generateName: mpi-allpair-allreduce-hari-
  namespace: gcr-admin-test1
spec:
  queue: default
  minAvailable: 479
  plugins:
    ssh: []
    svc: []
    env: []
  tasks:
    - name: server
      replicas: 1
      template:
        metadata:
          labels:
            app: allpair-mpi
            role: server
        spec:
          schedulerName: volcano
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 256Gi
            - name: data
              persistentVolumeClaim:
                claimName: pvc-vast-gcr-admin-test1
            - name: sys
              hostPath:
                path: /sys
                type: Directory
          tolerations:
            - key: "rdma"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: allpair-mpi
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: server
              image: nvcr.io/nvidia/pytorch:25.10-py3
              env:
                - name: gcrnode
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: ALLPAIR_DEBUG
                  value: "1"
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: data
                  mountPath: /data
                - name: sys
                  mountPath: /sys
                  readOnly: true
              ports:
                - name: rdma
                  containerPort: 18515
              command: ["/bin/bash", "-lc"]
              args:
                - |
                  set -eo pipefail
                  echo "=== Server Node ==="
                  hostname
                  nvidia-smi
                  
                  echo "=== PVC Check ==="
                  df -h /data
                  ls -la /data
                  
                  echo "=== Setup SSH ==="
                  export DEBIAN_FRONTEND=noninteractive
                  apt-get update -y
                  apt-get install -y --no-install-recommends openssh-server openssh-client
                  mkdir -p /run/sshd && ssh-keygen -A
                  /usr/sbin/sshd -D -e &
                  
                  echo "=== Build Hostfile ==="
                  for host in ${VC_SERVER_HOSTS//,/ }; do echo "$host slots=8"; done > /opt/hostfile
                  for host in ${VC_CLIENT_HOSTS//,/ }; do echo "$host slots=8"; done >> /opt/hostfile
                  cat /opt/hostfile
                  
                  echo "=== Server ready, sleeping forever ==="
                  sleep infinity
              resources:
                requests:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"
    - name: client
      replicas: 478
      template:
        metadata:
          labels:
            app: torchrun-session
            role: client
        spec:
          schedulerName: volcano
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 256Gi
            - name: data
              persistentVolumeClaim:
                claimName: pvc-vast-gcr-admin-test1
            - name: sys
              hostPath:
                path: /sys
                type: Directory
          tolerations:
            - key: "rdma"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: torchrun-session
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: client
              image: nvcr.io/nvidia/pytorch:25.10-py3
              volumeMounts:
                - name: dshm
                  mountPath: /dev/shm
                - name: data
                  mountPath: /data
                - name: sys
                  mountPath: /sys
                  readOnly: true
              ports:
                - name: rdma
                  containerPort: 18515
              command: ["/bin/bash", "-lc"]
              args:
                - |
                  set -eo pipefail
                  echo "=== Client Node ==="
                  hostname
                  nvidia-smi
                  
                  echo "=== PVC Check ==="
                  df -h /data
                  
                  echo "=== Setup SSH ==="
                  export DEBIAN_FRONTEND=noninteractive
                  apt-get update -y
                  apt-get install -y --no-install-recommends openssh-server openssh-client
                  mkdir -p /run/sshd && ssh-keygen -A
                  /usr/sbin/sshd -D -e &
                  
                  echo "=== Wait for Server DNS ==="
                  SERVER_HOST="$(echo $VC_SERVER_HOSTS | tr ',' '\n' | head -n1)"
                  if [[ -z "$SERVER_HOST" ]]; then
                    echo "VC_SERVER_HOSTS empty or missing"; exit 1
                  fi
                  echo "Server host: $SERVER_HOST"
                  for i in $(seq 1 60); do getent hosts "$SERVER_HOST" && break; echo "Waiting for DNS $SERVER_HOST"; sleep 2; done
                  
                  echo "=== Build Hostfile ==="
                  for host in ${VC_SERVER_HOSTS//,/ }; do echo "$host slots=8"; done > /opt/hostfile
                  for host in ${VC_CLIENT_HOSTS//,/ }; do echo "$host slots=8"; done >> /opt/hostfile
                  
                  echo "=== Client ready, sleeping forever ==="
                  sleep infinity
              resources:
                requests:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"
                limits:
                  nvidia.com/gpu: "8"
                  cpu: "100"
                  memory: "1500Gi"
                  rdma/rdma_shared_device_a: "1"
