#!/usr/bin/env bash
set -eo pipefail

# -------------------------------------------------------------------------
# 1. CONFIGURE SSH CLIENT (Crucial for preventing interactive prompts)
# -------------------------------------------------------------------------
mkdir -p /root/.ssh
chmod 700 /root/.ssh

# Disable StrictHostKeyChecking so mpirun doesn't hang asking "yes/no" for new hosts
cat > /root/.ssh/config <<EOF
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR
EOF
chmod 600 /root/.ssh/config

# -------------------------------------------------------------------------
# 2. SETUP SSH KEYS (Passwordless Access)
# -------------------------------------------------------------------------
# We generate a key if one doesn't exist and authorize it.
# NOTE: This relies on /root being a shared volume (PVC) across pods. 
# If not shared, you must use K8s secrets to mount keys.
if [ ! -f /root/.ssh/id_rsa ]; then
    echo "Generating SSH keys..."
    ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N ""
fi

# Ensure the public key is in authorized_keys so workers accept the connection
if ! grep -qf /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys 2>/dev/null; then
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
fi

# -------------------------------------------------------------------------
# 3. WAIT FOR WORKERS (Connectivity Check)
# -------------------------------------------------------------------------
echo "Waiting for workers to be ready..."

# Parse hostnames from the hostfile generated by your env.sh
HOSTS=$(awk '{print $1}' /opt/hostfile)

for host in $HOSTS; do
    echo "Checking connectivity to $host..."
    # Pure Bash TCP check (no netcat required)
    # Tries to connect to port 22 on the host
    while ! timeout 1 bash -c "cat < /dev/tcp/$host/22" &>/dev/null; do
        echo "  ... $host not listening on port 22 yet. Retrying..."
        sleep 2
    done
done

echo "All workers are reachable!"

# -------------------------------------------------------------------------
# 4. RUN MPI
# -------------------------------------------------------------------------
echo "Starting MPI Job..."

# Replace 'hostname' below with your actual training command
# Example: /usr/bin/python3 /app/train.py

mpirun \
    --allow-run-as-root \
    --hostfile /opt/hostfile \
    --bind-to none \
    -mca plm_rsh_args "-p 22" \
    -np $(wc -l < /opt/hostfile) \
    hostname